inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/StringLiterals:
  EnforcedStyle: single_quotes

Lint/Debugger:
  Enabled: true
