version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  app:
    build:
      context: ../../../
      dockerfile: config/docker/production/Dockerfile
      args:
        ADDITIONAL_FLAGS: "--enable-yjit"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - postgres
      - redis
    environment:
      RUBYOPT: "-W:no-deprecated --yjit"
      BUNDLE_JOBS: 4
      RAILS_ENV: production

volumes:
  postgres_data: